packageExtensions:
  '@atls/config-jest@*':
    dependencies:
      jest: 28.1.3
      typescript: '*'
  '@atls/webpack-proto-imports-loader@*':
    peerDependencies:
      webpack: 5.74.0

yarnPath: .yarn/releases/yarn-0.0.1-git.20231104.hash-b820e04b.cjs
